
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  adapter: postgresql
  database: evassist_development

test:
  adapter: postgresql
  database: evassist_test

production:
  adapter: postgresql
  database: evassist_production
